// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: healthcheck.proto

/*
Package healthcheck is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package healthcheck

import (
	"io"
	"net/http"

	"github.com/golang/protobuf/proto"
	"github.com/golang/protobuf/ptypes/empty"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
)

var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray

func request_HealthCheck_Check_0(ctx context.Context, marshaler runtime.Marshaler, client HealthCheckClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq empty.Empty
	var metadata runtime.ServerMetadata

	msg, err := client.Check(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

// RegisterHealthCheckHandlerFromEndpoint is same as RegisterHealthCheckHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterHealthCheckHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterHealthCheckHandler(ctx, mux, conn)
}

// RegisterHealthCheckHandler registers the http handlers for service HealthCheck to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterHealthCheckHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterHealthCheckHandlerClient(ctx, mux, NewHealthCheckClient(conn))
}

// RegisterHealthCheckHandlerClient registers the http handlers for service HealthCheck
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "HealthCheckClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "HealthCheckClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "HealthCheckClient" to call the correct interceptors.
func RegisterHealthCheckHandlerClient(ctx context.Context, mux *runtime.ServeMux, client HealthCheckClient) error {

	mux.Handle("GET", pattern_HealthCheck_Check_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HealthCheck_Check_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HealthCheck_Check_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_HealthCheck_Check_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0}, []string{"_healthcheck"}, ""))
)

var (
	forward_HealthCheck_Check_0 = runtime.ForwardResponseMessage
)
